- Floor: 1F
  equipment_type: ASRS_IPORT
  wes_id: IPT_101
  equipment_POST_url: http://192.168.168.60:5840/EAP/EAP/ASRS_1/GW2799/Methods/IPT_101
  equipment_GET_url: http://192.168.168.60:5840/EAP/EAP/ASRS_1/GW2799/GeneralParam/IPT_101
  sensor_POST_url: http://192.168.168.60:5840/EAP/EAP/RFID_IPT_101/GW2799/Methods/executeAllSteps
- Floor: 1F
  equipment_type: ASRS_OPORT
  wes_id: OPT_101
  equipment_POST_url: http://192.168.168.60:5840/EAP/EAP/ASRS_2/GW2799/Methods/OPT_101
  equipment_GET_url: http://192.168.168.60:5840/EAP/EAP/ASRS_2/GW2799/GeneralParam/OPT_101
  sensor_POST_url: http://192.168.168.60:5840/EAP/EAP/RFID_OPT_101/GW2799/Methods/executeAllSteps
- Floor: 1F
  equipment_type: ASRS_IPORT
  wes_id: IPT_102
  equipment_POST_url: http://192.168.168.60:5840/EAP/EAP/ASRS_2/GW2799/Methods/IPT_102
  equipment_GET_url: http://192.168.168.60:5840/EAP/EAP/ASRS_2/GW2799/GeneralParam/IPT_102
  sensor_POST_url: http://192.168.168.60:5840/EAP/EAP/RFID_IPT_102/GW2799/Methods/executeAllSteps
- Floor: 1F
  equipment_type: ASRS_OPORT
  wes_id: OPT_102
  equipment_POST_url: http://192.168.168.60:5840/EAP/EAP/ASRS_3/GW2799/Methods/OPT_102
  equipment_GET_url: http://192.168.168.60:5840/EAP/EAP/ASRS_3/GW2799/GeneralParam/OPT_102
  sensor_POST_url: http://192.168.168.60:5840/EAP/EAP/RFID_OPT_102/GW2799/Methods/executeAllSteps
- Floor: 1F
  equipment_type: ASRS_IPORT
  wes_id: IPT_103
  equipment_POST_url: http://192.168.168.60:5840/EAP/EAP/ASRS_3/GW2799/Methods/IPT_103
  equipment_GET_url: http://192.168.168.60:5840/EAP/EAP/ASRS_3/GW2799/GeneralParam/IPT_103
  sensor_POST_url: http://192.168.168.60:5840/EAP/EAP/RFID_IPT_103/GW2799/Methods/executeAllSteps
- Floor: 1F
  equipment_type: ASRS_OPORT
  wes_id: OPT_103
  equipment_POST_url: http://192.168.168.60:5840/EAP/EAP/ASRS_4/GW2799/Methods/OPT_103
  equipment_GET_url: http://192.168.168.60:5840/EAP/EAP/ASRS_4/GW2799/GeneralParam/OPT_103
  sensor_POST_url: http://192.168.168.60:5840/EAP/EAP/RFID_OPT_103/GW2799/Methods/executeAllSteps
- Floor: 1F
  equipment_type: ASRS_IPORT
  wes_id: IPT_104
  equipment_POST_url: http://192.168.168.60:5840/EAP/EAP/ASRS_4/GW2799/Methods/IPT_104
  equipment_GET_url: http://192.168.168.60:5840/EAP/EAP/ASRS_4/GW2799/GeneralParam/IPT_104
  sensor_POST_url: http://192.168.168.60:5840/EAP/EAP/RFID_IPT_104/GW2799/Methods/executeAllSteps
- Floor: 1F
  equipment_type: ASRS_OPORT
  wes_id: OPT_104
  equipment_POST_url: http://192.168.168.60:5840/EAP/EAP/ASRS_5/GW2799/Methods/OPT_104
  equipment_GET_url: http://192.168.168.60:5840/EAP/EAP/ASRS_5/GW2799/GeneralParam/OPT_104
  sensor_POST_url: http://192.168.168.60:5840/EAP/EAP/RFID_OPT_104/GW2799/Methods/executeAllSteps
- Floor: 1F
  equipment_type: ASRS_IPORT
  wes_id: IPT_105
  equipment_POST_url: http://192.168.168.60:5840/EAP/EAP/ASRS_5/GW2799/Methods/IPT_105
  equipment_GET_url: http://192.168.168.60:5840/EAP/EAP/ASRS_5/GW2799/GeneralParam/IPT_105
  sensor_POST_url: http://192.168.168.60:5840/EAP/EAP/RFID_IPT_105/GW2799/Methods/executeAllSteps
- Floor: 1F
  equipment_type: ASRS_OPORT
  wes_id: OPT_105
  equipment_POST_url: http://192.168.168.60:5840/EAP/EAP/ASRS_6/GW2799/Methods/OPT_105
  equipment_GET_url: http://192.168.168.60:5840/EAP/EAP/ASRS_6/GW2799/GeneralParam/OPT_105
  sensor_POST_url: http://192.168.168.60:5840/EAP/EAP/RFID_OPT_105/GW2799/Methods/executeAllSteps
- Floor: 1F
  equipment_type: ASRS_IPORT
  wes_id: IPT_106
  equipment_POST_url: http://192.168.168.60:5840/EAP/EAP/ASRS_6/GW2799/Methods/IPT_106
  equipment_GET_url: http://192.168.168.60:5840/EAP/EAP/ASRS_6/GW2799/GeneralParam/IPT_106
  sensor_POST_url: http://192.168.168.60:5840/EAP/EAP/RFID_OPT_106/GW2799/Methods/executeAllSteps
- Floor: 1F
  equipment_type: ASRS_OPORT
  wes_id: OPT_106
  equipment_POST_url: http://192.168.168.60:5840/EAP/EAP/ASRS_7/GW2799/Methods/OPT_106
  equipment_GET_url: http://192.168.168.60:5840/EAP/EAP/ASRS_7/GW2799/GeneralParam/OPT_106
  sensor_POST_url: http://192.168.168.60:5840/EAP/EAP/RFID_OPT_106/GW2799/Methods/executeAllSteps
- Floor: 1F
  equipment_type: ASRS_IPORT
  wes_id: IPT_107
  equipment_POST_url: http://192.168.168.60:5840/EAP/EAP/ASRS_7/GW2799/Methods/IPT_107
  equipment_GET_url: http://192.168.168.60:5840/EAP/EAP/ASRS_7/GW2799/GeneralParam/IPT_107
  sensor_POST_url: http://192.168.168.60:5840/EAP/EAP/RFID_IPT_107/GW2799/Methods/executeAllSteps
- Floor: 1F
  equipment_type: ASRS_OPORT
  wes_id: OPT_107
  equipment_POST_url: http://192.168.168.60:5840/EAP/EAP/ASRS_8/GW2799/Methods/OPT_107
  equipment_GET_url: http://192.168.168.60:5840/EAP/EAP/ASRS_8/GW2799/GeneralParam/OPT_107
  sensor_POST_url: http://192.168.168.60:5840/EAP/EAP/RFID_OPT_107/GW2799/Methods/executeAllSteps
- Floor: 1F
  equipment_type: LIFT
  wes_id: LFT_101
  equipment_POST_url: http://192.168.168.60:5840/EAP/EAP/LIFT_1/Methods/Unload_LFT_101
  equipment_GET_url: http://192.168.168.60:5840/EAP/EAP/LIFT_1/GeneralParam/AllInformation_LFT_101
  sensor_POST_url: http://192.168.168.60:5840/EAP/EAP/LIFT_1/Methods/load_LFT_101
- Floor: 1F
  equipment_type: LIFT
  wes_id: LFT_102
  equipment_POST_url: http://192.168.168.60:5840/EAP/EAP/LIFT_1/Methods/Unload_LFT_102
  equipment_GET_url: http://192.168.168.60:5840/EAP/EAP/LIFT_1/GeneralParam/AllInformation_LFT_102
  sensor_POST_url: http://192.168.168.60:5840/EAP/EAP/LIFT_1/Methods/load_LFT_102
- Floor: 5F
  equipment_type: LIFT
  wes_id: LFT_501
  equipment_POST_url: http://192.168.168.60:5840/EAP/EAP/LIFT_2/Methods/Unload_LFT_501
  equipment_GET_url: http://192.168.168.60:5840/EAP/EAP/LIFT_2/GeneralParam/AllInformation_LFT_501
  sensor_POST_url: http://192.168.168.60:5840/EAP/EAP/LIFT_2/Methods/load_LFT_501
- Floor: 5F
  equipment_type: LIFT
  wes_id: LFT_502
  equipment_POST_url: http://192.168.168.60:5840/EAP/EAP/LIFT_2/Methods/Unload_LFT_502
  equipment_GET_url: http://192.168.168.60:5840/EAP/EAP/LIFT_2/GeneralParam/AllInformation_LFT_502
  sensor_POST_url: http://192.168.168.60:5840/EAP/EAP/LIFT_2/Methods/load_LFT_502
- Floor: 1F
  equipment_type: Aligner
  wes_id: ALN_101
  equipment_POST_url: http://192.168.168.60:5840/EAP/EAP/ALN_101/GW2799/Methods/executeAllSteps
  equipment_GET_url: http://192.168.168.60:5840/EAP/EAP/ALN_101/GW2799/GeneralParam/AllInformation
  sensor_POST_url: http://192.168.168.60:5840/EAP/EAP/RFID_ALN_101/GW2799/Methods/executeAllSteps
- Floor: 1F
  equipment_type: PalletSupply
  wes_id: RPL_101
  equipment_POST_url: http://192.168.168.60:5840/EAP/EAP/RPL_101/GW2799/Methods/executeAllSteps
  equipment_GET_url: http://192.168.168.60:5840/EAP/EAP/RPL_101/GW2799/GeneralParam/AllInformation
  sensor_POST_url: '-'
- Floor: 5F
  equipment_type: PalletSupply
  wes_id: RPL_501
  equipment_POST_url: http://192.168.168.60:5840/EAP/EAP/RPL_501/GW2799/Methods/executeAllSteps
  equipment_GET_url: http://192.168.168.60:5840/EAP/EAP/RPL_501/GW2799/GeneralParam/AllInformation
  sensor_POST_url: http://192.168.168.60:5840/EAP/EAP/RFID_RPL_501/GW2799/Methods/executeAllSteps
- Floor: 5F
  equipment_type: PalletSupply
  wes_id: RPL_502
  equipment_POST_url: http://192.168.168.60:5840/EAP/EAP/RPL_502/GW2799/Methods/executeAllSteps
  equipment_GET_url: http://192.168.168.60:5840/EAP/EAP/RPL_502/GW2799/GeneralParam/AllInformation
  sensor_POST_url: http://192.168.168.60:5840/EAP/EAP/RFID_RPL_502/GW2799/Methods/executeAllSteps
- Floor: 5F
  equipment_type: Check
  wes_id: CHK_501
  equipment_POST_url: http://192.168.168.60:5840/EAP/EAP/CHK_501/GW2799/Methods/executeAllSteps
  equipment_GET_url: http://192.168.168.60:5840/EAP/EAP/CHK_501/GW2799/GeneralParam/AllInformation
  sensor_POST_url: '-'
- Floor: 5F
  equipment_type: Wrap
  wes_id: WRP_501
  equipment_POST_url: http://192.168.168.60:5840/EAP/EAP/WRP_501/GW2799/Methods/executeAllSteps
  equipment_GET_url: http://192.168.168.60:5840/EAP/EAP/WRP_501/GW2799/GeneralParam/AllInformation
  sensor_POST_url: '-'
- Floor: 5F
  equipment_type: Wrap
  wes_id: WRP_502
  equipment_POST_url: http://192.168.168.60:5840/EAP/EAP/WRP_502/GW2799/Methods/executeAllSteps
  equipment_GET_url: http://192.168.168.60:5840/EAP/EAP/WRP_502/GW2799/GeneralParam/AllInformation
  sensor_POST_url: '-'
